AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS resources to distribute a quote of the day to an email list.

Parameters:
  SourceEmailAddress:
    Type: String
  MemorySize:
    Type: Number
  ReservedConcurrency:
    Type: Number
  Timeout:
    Type: Number


Resources:
  SESEmailIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref SourceEmailAddress

  LambdaSendEmailRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-ses-send-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowSESSend
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: !Sub arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/${SourceEmailAddress}

  QuoteOfTheDayService:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: QuoteOfTheDay
      CodeUri: dist/
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: !Ref MemorySize
      ReservedConcurrentExecutions: !Ref ReservedConcurrency
      Timeout: !Ref Timeout
      Role: !GetAtt LambdaSendEmailRole.Arn
      Description: Distributes a quote of the day to an email list.
      Environment:
        Variables:
          SOURCE_EMAIL_ADDRESS: !Ref SourceEmailAddress
          AWS_REGION_VALUE: !Ref AWS::Region
